### ISSUE TITLE
Redirect seems to break the zci import step

### ISSUE THREAD

**Issue by blixt** [mamantoha/zendesk_help_center_api_client_rb#1]
I tried the command line and I'm getting the following redirect after which it says the category doesn't exist (but going to that URL shows the category).

Note that I had to change the `namespace` attribute in `zendesk_api/help_center.rb` to `"hc"` instead of `"help_center"` or the URL would be incorrect. I'm not sure why it's different for our setup.

```
zci -v import:sources
I, [2016-08-18T20:45:42.555042 #35971]  INFO -- : get https://hello.rogertalk.com/hc/categories/203618748
D, [2016-08-18T20:45:42.555126 #35971] DEBUG -- :   Accept: "application/json"
  Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
  User-Agent: "ZendeskAPI Ruby 1.14.0"
I, [2016-08-18T20:45:42.853294 #35971]  INFO -- : Status 301
D, [2016-08-18T20:45:42.853450 #35971] DEBUG -- :   server: "nginx"
  date: "Fri, 19 Aug 2016 00:45:42 GMT"
  content-type: "text/html; charset=utf-8"
  transfer-encoding: "chunked"
  connection: "close"
  status: "301 Moved Permanently"
  x-ua-compatible: "IE=edge"
  x-xss-protection: "1; mode=block"
  x-frame-options: "SAMEORIGIN"
  location: "https://hello.rogertalk.com/hc/en-us/categories/203618748"
  set-cookie: "..."
  p3p: "CP=\"NOI DSP COR NID ADMa OPTa OUR NOR\""
  x-zendesk-user-id: ""
  strict-transport-security: "max-age=86400;"
  x-zendesk-origin-server: "hcapp12.pod6.iad1.zdsys.com"
  x-request-id: "5dff3219-xxxx-xxxx-xxxx-xxxxxxxxxxx”
  x-runtime: "0.217668"
  cache-control: "must-revalidate, private, max-age=0"
  x-content-type-options: "nosniff"
"<html><body>You are being <a href=\"https://hello.rogertalk.com/hc/en-us/categories/203618748\">redirected</a>.</body></html>"
error: No such category
```

**Comment by phamngocanh151195** [comment]
I don't know. You should use google.
P/s: my english not good :)

**Comment by mamantoha** [comment]
Hi @blixt 

Please doubled check the Category ID.

According to the official [documentation](https://developer.zendesk.com/rest_api/docs/help_center/categories),  API endpoint is `/api/v2/help_center/`. So changing the namespace won't help you.

**Comment by mamantoha** [comment]
Go to `https://<domain>.zendesk.com/hc/admin/arrange_contents` and find category id in the link. I know it's not very intuitive 😄 

If you have any questions please let me know.

**Comment by blixt** [comment]
We got it to work, we incorrectly put the custom Zendesk URL in the config (as opposed to the original hostname x.zendesk.com). Thank you @mamantoha!
